name: Manual trigger for Destroy Planned Terraform
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: true
        default: 'dev'

jobs:
  issue_parser:
    runs-on: ubuntu-latest
    name: Terraform destroy
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Terraform destroy on github action aws
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        TF_ACTION_WORKING_DIR: 'terraform'
        AWS_REGION: 'eu-west-1'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      uses: md1810/terraform-destroy-on-action@destroy-terraform-on-action
      with:
        org_name: 'md1810'
        repo_name: 'terraform-on-git-action'
